# Generated by Django 6.1 on 2026-08-09 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_at']},
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('heading', 'Titre'), ('text', 'Texte'), ('quote', 'Citation'), ('image', 'Image'), ('code', 'Code')], default='text', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/paragraphs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='Post.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
