# Generated by Django 6.1 on 2026-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_options_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
