# Generated by Django 6.1 on 2026-08-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_paragraph_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='type',
        ),
    ]
